name: Branch Quality Check

on:
  push:
    branches:
      - main
      - master
      - develop

permissions:
  contents: read

jobs:
  code-quality-and-build:
    uses: ./.github/workflows/code-quality-and-build.yml
