name: E2E

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  e2e:
    name: E2E coverage
    uses: 12masta/example-app-e2e/.github/workflows/e2e.yml@main
    with:
      frontend_ref: ${{ github.sha }}
      backend_ref: main
      coverage: true
